### ISSUE TITLE
Feature: Connected Logs

### ISSUE THREAD

**Issue by SpyCoder77** [Aeldit/MC-Resource-Packs#1]
Add connected logs. Here is what I mean.
two logs facing up next to each other - the top texture connects.

**Comment by Aeldit** [comment]
This is planned and I started working on it a few months ago, so I'll try to finish it during the next week

**Comment by SpyCoder77** [comment]
I can help you with adding more textures, like terrocotta? If that isn't already added

**Comment by SpyCoder77** [comment]
I can also help with the smooth GUI

**Comment by Aeldit** [comment]
For the terracotta I don't really see what we could add given the textures already "connect" by default, but you could send me an in-game example here if you want.

And for the smooth GUI that would be cool, but we will see that next week because I'm not home right now

**Comment by Aeldit** [comment]
Added with version 0.5.0
