### ISSUE TITLE
logs facing different directions still connect

### ISSUE THREAD

**Issue by SpyCoder77** [Aeldit/MC-Resource-Packs#2]
![Screenshot 2023-07-24 163919](https://github.com/Aeldit/MC-Resource-Packs/assets/130170051/78085ba3-72c0-43fb-8b59-3c807c6b7874)

**Comment by Aeldit** [comment]
Fixed with [3a4ef7f](https://github.com/Aeldit/MC-Resource-Packs/commit/3a4ef7ff5a595fab3507432070bbfa6b2cf6413a)
