### ISSUE TITLE
Smooth stone glitch

### ISSUE THREAD

**Issue by SpyCoder77** [Aeldit/MC-Resource-Packs#3]
https://github.com/Aeldit/MC-Resource-Packs/assets/130170051/2aecd551-590a-4956-b375-c0d447465b93

**Comment by Aeldit** [comment]
Fixed with [dda49ba](https://github.com/Aeldit/MC-Resource-Packs/commit/dda49ba1d72c9bac1cd7dd64b0ff90067db90703)

**Comment by SpyCoder77** [comment]
Is it on modrinth? That video was in the latest modrinth release

**Comment by Aeldit** [comment]
Yep, I released it just after closing this issue, it is the version 0.5.1
