### ISSUE TITLE
Discussion 

### ISSUE THREAD

**Issue by SpyCoder77** [Aeldit/MC-Resource-Packs#5]
If you want to talk, talk!

**Comment by SpyCoder77** [comment]
What do you use to make the textures?

**Comment by SpyCoder77** [comment]
Can you add me as a contributor on the modrinth page

**Comment by Aeldit** [comment]
To make the textures I use Gimp, but please do not use Github issues to discuss anything other than issues

**Comment by SpyCoder77** [comment]
How else do I talk then?

**Comment by Aeldit** [comment]
Why would you want to be added in contributors ? Well try and install discord, that is the place made for this
