### ISSUE TITLE
CTM Optifine - Fabric 0.5.1 1.20.3-4 Modrinth release has misnamed .mcmeta file

### ISSUE THREAD

**Issue by treacherousfiend** [Aeldit/MC-Resource-Packs#6]
**Describe the bug**
The Modrinth release of CTM Optifine - Fabric 0.5.1 for 1.20.3 and 1.20.4 has its .mcmeta file name directly from the repository, being named "pack_1.20.3-1.20.4.mcmeta" rather than just "pack.mcmeta", so Minecraft fails to recognize the resource pack

**Your environment**
Minecraft (ex: 1.19.4) : Minecraft 1.20.4, Quilt Loader 0.22.1-beta.4

Project Name (ex: CTM OF-Fabric) : CTM OF-Fabric

**To Reproduce**

1. Download resource pack from Modrinth
2. Install zip to Minecraft
3. Open Minecraft and navigate to the resource pack menu
4. Resource pack will not be read by Minecraft, and is missing from the menu

**Expected behavior**
Minecraft will be able to load and read the resource pack out of the box.

**Screenshots**
N/A

**Comment by Aeldit** [comment]
Thanks for the bug report, I'll fix this in a few minutes

**Comment by Aeldit** [comment]
This is now fixed, so I close the issue
