### ISSUE TITLE
Feature: BiomesOPlenty connected logs

### ISSUE THREAD

**Issue by vico93** [Aeldit/MC-Resource-Packs#7]
Don't know if you guys do mod support, but if positive, adding support for BoP logs would be amazing!

**Comment by Aeldit** [comment]
I'll try to add them when I have the time (could you send me a link to the version of the mod you use so I can get the correct one ?)

**Comment by Aeldit** [comment]
I got the permission to do so from the developer of the mod, so I'm gonna start working on it very soon

**Comment by Aeldit** [comment]
Closed by [012a163](https://github.com/Aeldit/MC-Resource-Packs/commit/012a1633cc9e0a2e35f625e3c6147f25384c7155)

**Comment by Aeldit** [comment]
Closed by [012a163](https://github.com/Aeldit/MC-Resource-Packs/commit/012a1633cc9e0a2e35f625e3c6147f25384c7155)
