### ISSUE TITLE
[Feature Request] New 1.21 Copper and tuff blocks

### ISSUE THREAD

**Issue by SpyC0der77** [Aeldit/MC-Resource-Packs#8]
Btw it is me spycoder77 I lost access to my old account lol

I know 1.21 isn't out yet, but when it does, you should add the copper and tuff blocks.

**Comment by Aeldit** [comment]
It is planned

**Comment by SpyC0der77** [comment]
When will it be coming out?

**Comment by Aeldit** [comment]
I am working on it, the tuff block is done and I now only have to do the copper grates / lights, but these are the same base texture as the copper blocks to I will not have to redo all the textures.
However, I don't really have a release date but it is soon

**Comment by Aeldit** [comment]
Closed by https://github.com/Aeldit/MC-Resource-Packs/commit/6fe8cf6b99d2a3b887908685cc87543a21c68c25
