### ISSUE TITLE
[Idea] Lambda Better Grass Resource pack

### ISSUE THREAD

**Issue by SpyC0der77** [Aeldit/MC-Resource-Packs#9]
It would be cool if there could be a resource pack of lambda better grass for continuity, since it is basically just connected textures. I could try and make it, if you tell me the basics of how to make a connected texture or give me a source to learn

**Comment by Aeldit** [comment]
Lambda better grass already works with continuity, so that won't be necessary.

And for the last time, this is a place for ISSUES not requests
